### ISSUE TITLE
Date handling is very confusion

### ISSUE THREAD

**Issue by jainraje** [jeffreyrdcs/stock-vcpscreener#2]
I'm running the screener after Monday market close (~after 11PM EST).

I forced the yahoo ohlcv download for the index and all tickers. Upon inspection, OHLCV data is present for both 2023-02-24 or 2023-02-27.

Now trying to running the stock selection and report/files for the dash app:
python stock_vcpscreener.py 
No update needed
Updating CSV data
No update needed for the database!
Working on 2023-02-26
This is not a valid trade day

No `selected_stock` files for 2023-02-24 or 2023-02-27 generated.

The date handling and logic seems flawed.  Will you please explain?

Thank-you,
--Rajeev

**Comment by jeffreyrdcs** [comment]
Hi, thank you for your question. If you run it by default, it will generate the report for the day before the last trade day. The reason is that this script is designed to run on a schedule every day after the market close. So in your case, the code would try to work on 2023-02-26, which is a Sunday, so it outputs, "This is not a valid trade day".

You can change the date on this line to specify the date you want to get the report (such as timedelta(days=3) to get 2023-02-23):

https://github.com/jeffreyrdcs/stock-vcpscreener/blob/main/stock_vcpscreener.py#L416

There are plans to update and refactor this repo, but it is not completed yet.

**Comment by jainraje** [comment]
HI There, I appreciate your response/answers. At this point I'm not able to generate a solid set of output data becuase the program is confused based on its current context. Will you please help me out?

To help understand the state of the data:

Ticker contents:
![image](https://user-images.githubusercontent.com/15187961/221950732-c1f92921-3c57-4982-a0d0-5546f56f2f1e.png)

daily_selected_stock_info.csv contents:
![image](https://user-images.githubusercontent.com/15187961/221950583-52f12584-3124-4778-8690-1732c49fd589.png)

Selected_stock_<>.csv contents:
![image](https://user-images.githubusercontent.com/15187961/221951076-31257b8d-3b70-45f2-a4b9-7d2c7e066665.png)


What should should I change or delete to get the app ro generate a full and correct set of output data?

TIA,
jainraje

**Comment by jainraje** [comment]
![image](https://user-images.githubusercontent.com/15187961/221952013-072b194d-4a4e-4b39-941f-3d29a438ec91.png)

**Comment by jeffreyrdcs** [comment]
Sure. I just took a look at my selected_stock_2023-02-23.csv. The output that you get is identical to what I have here. The last two are HTHT and VC for mine, so I guess it works fine for you. You should also see a 2023-02-23.pdf in the same folder. 

For 2023-02-27, I can confirm that the code ran fine without any problems last night. Here is the output for 2023-02-27:
https://github.com/jeffreyrdcs/stock-vcpscreener/blob/main/output/selected_stock_2023-02-27.csv

Do you want to specify the date and try to rerun the code? Let me know if there is any error message showing up.

**Comment by jainraje** [comment]
FYI, your *live* site is missing '2023-02-24' (Friday) data. And my local copy has created output for '2023-02-26' (Sunday) in some of the output csv files even though Sunday is not a valid trading day. That Sunday data does not seem to go away when I rerun.

The logic for date handling is very flawed. There are a few minor items to refactor to get your scanner to work in a clean and consistent manner. I will help you clean it up. I will look at it later today and come back to yu. thank-you for your response.

**Comment by jeffreyrdcs** [comment]
Actually it was my intention to skip every Friday, so there are no 17/2 etc., on the site as well. And that's why there is a `timedelta(1)` after `get_last_trade_day()` on that line, so it will get the day before the last trade day and this always skip Friday if you run it on Monday.

You can easily replace that line with a different logic to get every trade day with your cron job setup. If you get a Sunday output, you probably set it incorrectly since it should output the `'This is not a valid trade day` message, and the script should quit.

Anyway, if you catch any bugs, feel free to open a PR. I will have a look at them later!

**Comment by jainraje** [comment]
I ran the scanner again today. It is creating the "daily_selected_stock_info.csv" correctly. As can be seen the last row contains metrics for yesterday '2023-02-28'.

![image](https://user-images.githubusercontent.com/15187961/222286277-0ed0e39c-0c93-42bf-80e7-0c36c353f04f.png)

However, the scanner is not creating ./output/selected_stock_2023-02-28.csv correctly. It is attempting to create it but it is empty. Attached is a log file of the output.
[output.log](https://github.com/jeffreyrdcs/stock-vcpscreener/files/10866025/output.log)

All the raw yahoo csv files for the tickers and index are there with 2023-02-28 data.

Please advise me with this last step (ie correctly create the "selected_stock_2023-02-28.csv" I will appreciate.

TIA

**Comment by jeffreyrdcs** [comment]
From the log you provided, I can see that the stock report is generated correctly. After that there are a lot of `Fail to get stock data for [stock_name]` messages, which means either the individual [stock_name]_.csv under `db_yfinance` directory does not have data of 2023-02-28, or it does not have time ranges long enough to calculate the required metrics.

You can check for example if `ACGL_.csv` have the row for 2023-02-28.csv. Make sure those data are saved correctly and have a time period long enough to calculate the 52 Week Min and Max. 

Again, there might be an issue somewhere in the code, but since I can see that there is an `selected_stock_2023-02-28.csv` output for my cron job last night, I suspect this is more related to the issue of the ticker data.
