### ISSUE TITLE
The execution of https://jeffreyrdcs.pythonanywhere.com/  and generated pdf data is different 

### ISSUE THREAD

**Issue by asraghu123** [jeffreyrdcs/stock-vcpscreener#5]
When I just run the https://jeffreyrdcs.pythonanywhere.com/  I see output for today.  

When I execute the screener on my PC, I get the pdf outputs.   

I want to know if https://jeffreyrdcs.pythonanywhere.com/  is something you run daily with a different set of stocks and is available as a sample for use ?

How can we do a similar report for the output generated locally ?

**Comment by jeffreyrdcs** [comment]
Hi, that is because the latest report on https://jeffreyrdcs.pythonanywhere.com/  is for Feb 21 2024.  I switched off the cron job a while ago so it is not updated daily. 

The code of the dash report is available in this repo: https://github.com/jeffreyrdcs/stock-vcp-dash

You can host it locally and replace this line: https://github.com/jeffreyrdcs/stock-vcp-dash/blob/main/app.py#L19 with a local directory where you store the output.

**Comment by asraghu123** [comment]
Thanks a lot. I might be asking more here but can you provide for a layman
like me how to setup cron job scheduller, i think that automates daily runs.

Thanks in advance

**Comment by jeffreyrdcs** [comment]
Tbh I am not sure how to do that in Windows. It is pretty easy in linux or macOS though.  I found this stackoverflow page:

https://stackoverflow.com/questions/7195503/setting-up-a-cron-job-in-windows
